package com.roughindustries.air.client;

import com.roughindustries.air.model.Airport2airline;
import com.roughindustries.air.model.Airport2airlineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Airport2airlineMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.airport2airline
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	int countByExample(Airport2airlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.airport2airline
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	int deleteByExample(Airport2airlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.airport2airline
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	int insert(Airport2airline record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.airport2airline
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	int insertSelective(Airport2airline record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.airport2airline
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	List<Airport2airline> selectByExample(Airport2airlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.airport2airline
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	int updateByExampleSelective(@Param("record") Airport2airline record,
			@Param("example") Airport2airlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.airport2airline
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	int updateByExample(@Param("record") Airport2airline record, @Param("example") Airport2airlineExample example);
}