package com.roughindustries.air.client;

import com.roughindustries.air.model.LocationsServed;
import com.roughindustries.air.model.LocationsServedExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LocationsServedMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.locations_served
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	int countByExample(LocationsServedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.locations_served
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	int deleteByExample(LocationsServedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.locations_served
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	int deleteByPrimaryKey(Integer internalLocationServedId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.locations_served
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	int insert(LocationsServed record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.locations_served
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	int insertSelective(LocationsServed record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.locations_served
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	List<LocationsServed> selectByExample(LocationsServedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.locations_served
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	LocationsServed selectByPrimaryKey(Integer internalLocationServedId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.locations_served
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	int updateByExampleSelective(@Param("record") LocationsServed record,
			@Param("example") LocationsServedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.locations_served
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	int updateByExample(@Param("record") LocationsServed record, @Param("example") LocationsServedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.locations_served
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	int updateByPrimaryKeySelective(LocationsServed record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.locations_served
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	int updateByPrimaryKey(LocationsServed record);
}