package com.roughindustries.air.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;
import java.util.Iterator;

public class AirportsExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.airports
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.airports
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.airports
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.airports
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public AirportsExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.airports
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.airports
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.airports
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.airports
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.airports
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.airports
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.airports
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.airports
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.airports
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.airports
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.airports
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andInternalAirportIdIsNull() {
			addCriterion("internal_airport_id is null");
			return (Criteria) this;
		}

		public Criteria andInternalAirportIdIsNotNull() {
			addCriterion("internal_airport_id is not null");
			return (Criteria) this;
		}

		public Criteria andInternalAirportIdEqualTo(Integer value) {
			addCriterion("internal_airport_id =", value, "internalAirportId");
			return (Criteria) this;
		}

		public Criteria andInternalAirportIdNotEqualTo(Integer value) {
			addCriterion("internal_airport_id <>", value, "internalAirportId");
			return (Criteria) this;
		}

		public Criteria andInternalAirportIdGreaterThan(Integer value) {
			addCriterion("internal_airport_id >", value, "internalAirportId");
			return (Criteria) this;
		}

		public Criteria andInternalAirportIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("internal_airport_id >=", value, "internalAirportId");
			return (Criteria) this;
		}

		public Criteria andInternalAirportIdLessThan(Integer value) {
			addCriterion("internal_airport_id <", value, "internalAirportId");
			return (Criteria) this;
		}

		public Criteria andInternalAirportIdLessThanOrEqualTo(Integer value) {
			addCriterion("internal_airport_id <=", value, "internalAirportId");
			return (Criteria) this;
		}

		public Criteria andInternalAirportIdIn(List<Integer> values) {
			addCriterion("internal_airport_id in", values, "internalAirportId");
			return (Criteria) this;
		}

		public Criteria andInternalAirportIdNotIn(List<Integer> values) {
			addCriterion("internal_airport_id not in", values, "internalAirportId");
			return (Criteria) this;
		}

		public Criteria andInternalAirportIdBetween(Integer value1, Integer value2) {
			addCriterion("internal_airport_id between", value1, value2, "internalAirportId");
			return (Criteria) this;
		}

		public Criteria andInternalAirportIdNotBetween(Integer value1, Integer value2) {
			addCriterion("internal_airport_id not between", value1, value2, "internalAirportId");
			return (Criteria) this;
		}

		public Criteria andIcaoCodeIsNull() {
			addCriterion("icao_code is null");
			return (Criteria) this;
		}

		public Criteria andIcaoCodeIsNotNull() {
			addCriterion("icao_code is not null");
			return (Criteria) this;
		}

		public Criteria andIcaoCodeEqualTo(String value) {
			addCriterion("icao_code =", value, "icaoCode");
			return (Criteria) this;
		}

		public Criteria andIcaoCodeNotEqualTo(String value) {
			addCriterion("icao_code <>", value, "icaoCode");
			return (Criteria) this;
		}

		public Criteria andIcaoCodeGreaterThan(String value) {
			addCriterion("icao_code >", value, "icaoCode");
			return (Criteria) this;
		}

		public Criteria andIcaoCodeGreaterThanOrEqualTo(String value) {
			addCriterion("icao_code >=", value, "icaoCode");
			return (Criteria) this;
		}

		public Criteria andIcaoCodeLessThan(String value) {
			addCriterion("icao_code <", value, "icaoCode");
			return (Criteria) this;
		}

		public Criteria andIcaoCodeLessThanOrEqualTo(String value) {
			addCriterion("icao_code <=", value, "icaoCode");
			return (Criteria) this;
		}

		public Criteria andIcaoCodeLike(String value) {
			addCriterion("icao_code like", value, "icaoCode");
			return (Criteria) this;
		}

		public Criteria andIcaoCodeNotLike(String value) {
			addCriterion("icao_code not like", value, "icaoCode");
			return (Criteria) this;
		}

		public Criteria andIcaoCodeIn(List<String> values) {
			addCriterion("icao_code in", values, "icaoCode");
			return (Criteria) this;
		}

		public Criteria andIcaoCodeNotIn(List<String> values) {
			addCriterion("icao_code not in", values, "icaoCode");
			return (Criteria) this;
		}

		public Criteria andIcaoCodeBetween(String value1, String value2) {
			addCriterion("icao_code between", value1, value2, "icaoCode");
			return (Criteria) this;
		}

		public Criteria andIcaoCodeNotBetween(String value1, String value2) {
			addCriterion("icao_code not between", value1, value2, "icaoCode");
			return (Criteria) this;
		}

		public Criteria andFaaLidIsNull() {
			addCriterion("faa_lid is null");
			return (Criteria) this;
		}

		public Criteria andFaaLidIsNotNull() {
			addCriterion("faa_lid is not null");
			return (Criteria) this;
		}

		public Criteria andFaaLidEqualTo(String value) {
			addCriterion("faa_lid =", value, "faaLid");
			return (Criteria) this;
		}

		public Criteria andFaaLidNotEqualTo(String value) {
			addCriterion("faa_lid <>", value, "faaLid");
			return (Criteria) this;
		}

		public Criteria andFaaLidGreaterThan(String value) {
			addCriterion("faa_lid >", value, "faaLid");
			return (Criteria) this;
		}

		public Criteria andFaaLidGreaterThanOrEqualTo(String value) {
			addCriterion("faa_lid >=", value, "faaLid");
			return (Criteria) this;
		}

		public Criteria andFaaLidLessThan(String value) {
			addCriterion("faa_lid <", value, "faaLid");
			return (Criteria) this;
		}

		public Criteria andFaaLidLessThanOrEqualTo(String value) {
			addCriterion("faa_lid <=", value, "faaLid");
			return (Criteria) this;
		}

		public Criteria andFaaLidLike(String value) {
			addCriterion("faa_lid like", value, "faaLid");
			return (Criteria) this;
		}

		public Criteria andFaaLidNotLike(String value) {
			addCriterion("faa_lid not like", value, "faaLid");
			return (Criteria) this;
		}

		public Criteria andFaaLidIn(List<String> values) {
			addCriterion("faa_lid in", values, "faaLid");
			return (Criteria) this;
		}

		public Criteria andFaaLidNotIn(List<String> values) {
			addCriterion("faa_lid not in", values, "faaLid");
			return (Criteria) this;
		}

		public Criteria andFaaLidBetween(String value1, String value2) {
			addCriterion("faa_lid between", value1, value2, "faaLid");
			return (Criteria) this;
		}

		public Criteria andFaaLidNotBetween(String value1, String value2) {
			addCriterion("faa_lid not between", value1, value2, "faaLid");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andWikiUrlIsNull() {
			addCriterion("wiki_url is null");
			return (Criteria) this;
		}

		public Criteria andWikiUrlIsNotNull() {
			addCriterion("wiki_url is not null");
			return (Criteria) this;
		}

		public Criteria andWikiUrlEqualTo(String value) {
			addCriterion("wiki_url =", value, "wikiUrl");
			return (Criteria) this;
		}

		public Criteria andWikiUrlNotEqualTo(String value) {
			addCriterion("wiki_url <>", value, "wikiUrl");
			return (Criteria) this;
		}

		public Criteria andWikiUrlGreaterThan(String value) {
			addCriterion("wiki_url >", value, "wikiUrl");
			return (Criteria) this;
		}

		public Criteria andWikiUrlGreaterThanOrEqualTo(String value) {
			addCriterion("wiki_url >=", value, "wikiUrl");
			return (Criteria) this;
		}

		public Criteria andWikiUrlLessThan(String value) {
			addCriterion("wiki_url <", value, "wikiUrl");
			return (Criteria) this;
		}

		public Criteria andWikiUrlLessThanOrEqualTo(String value) {
			addCriterion("wiki_url <=", value, "wikiUrl");
			return (Criteria) this;
		}

		public Criteria andWikiUrlLike(String value) {
			addCriterion("wiki_url like", value, "wikiUrl");
			return (Criteria) this;
		}

		public Criteria andWikiUrlNotLike(String value) {
			addCriterion("wiki_url not like", value, "wikiUrl");
			return (Criteria) this;
		}

		public Criteria andWikiUrlIn(List<String> values) {
			addCriterion("wiki_url in", values, "wikiUrl");
			return (Criteria) this;
		}

		public Criteria andWikiUrlNotIn(List<String> values) {
			addCriterion("wiki_url not in", values, "wikiUrl");
			return (Criteria) this;
		}

		public Criteria andWikiUrlBetween(String value1, String value2) {
			addCriterion("wiki_url between", value1, value2, "wikiUrl");
			return (Criteria) this;
		}

		public Criteria andWikiUrlNotBetween(String value1, String value2) {
			addCriterion("wiki_url not between", value1, value2, "wikiUrl");
			return (Criteria) this;
		}

		public Criteria andLatitudeIsNull() {
			addCriterion("latitude is null");
			return (Criteria) this;
		}

		public Criteria andLatitudeIsNotNull() {
			addCriterion("latitude is not null");
			return (Criteria) this;
		}

		public Criteria andLatitudeEqualTo(Double value) {
			addCriterion("latitude =", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeNotEqualTo(Double value) {
			addCriterion("latitude <>", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeGreaterThan(Double value) {
			addCriterion("latitude >", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeGreaterThanOrEqualTo(Double value) {
			addCriterion("latitude >=", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeLessThan(Double value) {
			addCriterion("latitude <", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeLessThanOrEqualTo(Double value) {
			addCriterion("latitude <=", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeIn(List<Double> values) {
			addCriterion("latitude in", values, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeNotIn(List<Double> values) {
			addCriterion("latitude not in", values, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeBetween(Double value1, Double value2) {
			addCriterion("latitude between", value1, value2, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeNotBetween(Double value1, Double value2) {
			addCriterion("latitude not between", value1, value2, "latitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeIsNull() {
			addCriterion("longitude is null");
			return (Criteria) this;
		}

		public Criteria andLongitudeIsNotNull() {
			addCriterion("longitude is not null");
			return (Criteria) this;
		}

		public Criteria andLongitudeEqualTo(Double value) {
			addCriterion("longitude =", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeNotEqualTo(Double value) {
			addCriterion("longitude <>", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeGreaterThan(Double value) {
			addCriterion("longitude >", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeGreaterThanOrEqualTo(Double value) {
			addCriterion("longitude >=", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeLessThan(Double value) {
			addCriterion("longitude <", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeLessThanOrEqualTo(Double value) {
			addCriterion("longitude <=", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeIn(List<Double> values) {
			addCriterion("longitude in", values, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeNotIn(List<Double> values) {
			addCriterion("longitude not in", values, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeBetween(Double value1, Double value2) {
			addCriterion("longitude between", value1, value2, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeNotBetween(Double value1, Double value2) {
			addCriterion("longitude not between", value1, value2, "longitude");
			return (Criteria) this;
		}

		public Criteria andIataCodeIsNull() {
			addCriterion("iata_code is null");
			return (Criteria) this;
		}

		public Criteria andIataCodeIsNotNull() {
			addCriterion("iata_code is not null");
			return (Criteria) this;
		}

		public Criteria andIataCodeEqualTo(String value) {
			addCriterion("iata_code =", value, "iataCode");
			return (Criteria) this;
		}

		public Criteria andIataCodeNotEqualTo(String value) {
			addCriterion("iata_code <>", value, "iataCode");
			return (Criteria) this;
		}

		public Criteria andIataCodeGreaterThan(String value) {
			addCriterion("iata_code >", value, "iataCode");
			return (Criteria) this;
		}

		public Criteria andIataCodeGreaterThanOrEqualTo(String value) {
			addCriterion("iata_code >=", value, "iataCode");
			return (Criteria) this;
		}

		public Criteria andIataCodeLessThan(String value) {
			addCriterion("iata_code <", value, "iataCode");
			return (Criteria) this;
		}

		public Criteria andIataCodeLessThanOrEqualTo(String value) {
			addCriterion("iata_code <=", value, "iataCode");
			return (Criteria) this;
		}

		public Criteria andIataCodeLike(String value) {
			addCriterion("iata_code like", value, "iataCode");
			return (Criteria) this;
		}

		public Criteria andIataCodeNotLike(String value) {
			addCriterion("iata_code not like", value, "iataCode");
			return (Criteria) this;
		}

		public Criteria andIataCodeIn(List<String> values) {
			addCriterion("iata_code in", values, "iataCode");
			return (Criteria) this;
		}

		public Criteria andIataCodeNotIn(List<String> values) {
			addCriterion("iata_code not in", values, "iataCode");
			return (Criteria) this;
		}

		public Criteria andIataCodeBetween(String value1, String value2) {
			addCriterion("iata_code between", value1, value2, "iataCode");
			return (Criteria) this;
		}

		public Criteria andIataCodeNotBetween(String value1, String value2) {
			addCriterion("iata_code not between", value1, value2, "iataCode");
			return (Criteria) this;
		}

		public Criteria andLocationsServedLastUpdateIsNull() {
			addCriterion("locations_served_last_update is null");
			return (Criteria) this;
		}

		public Criteria andLocationsServedLastUpdateIsNotNull() {
			addCriterion("locations_served_last_update is not null");
			return (Criteria) this;
		}

		public Criteria andLocationsServedLastUpdateEqualTo(Date value) {
			addCriterion("locations_served_last_update =", value, "locationsServedLastUpdate");
			return (Criteria) this;
		}

		public Criteria andLocationsServedLastUpdateNotEqualTo(Date value) {
			addCriterion("locations_served_last_update <>", value, "locationsServedLastUpdate");
			return (Criteria) this;
		}

		public Criteria andLocationsServedLastUpdateGreaterThan(Date value) {
			addCriterion("locations_served_last_update >", value, "locationsServedLastUpdate");
			return (Criteria) this;
		}

		public Criteria andLocationsServedLastUpdateGreaterThanOrEqualTo(Date value) {
			addCriterion("locations_served_last_update >=", value, "locationsServedLastUpdate");
			return (Criteria) this;
		}

		public Criteria andLocationsServedLastUpdateLessThan(Date value) {
			addCriterion("locations_served_last_update <", value, "locationsServedLastUpdate");
			return (Criteria) this;
		}

		public Criteria andLocationsServedLastUpdateLessThanOrEqualTo(Date value) {
			addCriterion("locations_served_last_update <=", value, "locationsServedLastUpdate");
			return (Criteria) this;
		}

		public Criteria andLocationsServedLastUpdateIn(List<Date> values) {
			addCriterion("locations_served_last_update in", values, "locationsServedLastUpdate");
			return (Criteria) this;
		}

		public Criteria andLocationsServedLastUpdateNotIn(List<Date> values) {
			addCriterion("locations_served_last_update not in", values, "locationsServedLastUpdate");
			return (Criteria) this;
		}

		public Criteria andLocationsServedLastUpdateBetween(Date value1, Date value2) {
			addCriterion("locations_served_last_update between", value1, value2, "locationsServedLastUpdate");
			return (Criteria) this;
		}

		public Criteria andLocationsServedLastUpdateNotBetween(Date value1, Date value2) {
			addCriterion("locations_served_last_update not between", value1, value2, "locationsServedLastUpdate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.airports
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.airports
     *
     * @mbggenerated do_not_delete_during_merge Wed Mar 23 10:27:27 CDT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}