package com.roughindustries.air.model;

import java.util.Date;

public class Airports {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.airports.internal_airport_id
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	private Integer internalAirportId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.airports.icao_code
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	private String icaoCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.airports.faa_lid
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	private String faaLid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.airports.name
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.airports.wiki_url
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	private String wikiUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.airports.latitude
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	private Double latitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.airports.longitude
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	private Double longitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.airports.iata_code
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	private String iataCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.airports.locations_served_last_update
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	private Date locationsServedLastUpdate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.airports.internal_airport_id
	 * @return  the value of public.airports.internal_airport_id
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public Integer getInternalAirportId() {
		return internalAirportId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.airports.internal_airport_id
	 * @param internalAirportId  the value for public.airports.internal_airport_id
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public void setInternalAirportId(Integer internalAirportId) {
		this.internalAirportId = internalAirportId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.airports.icao_code
	 * @return  the value of public.airports.icao_code
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public String getIcaoCode() {
		return icaoCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.airports.icao_code
	 * @param icaoCode  the value for public.airports.icao_code
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public void setIcaoCode(String icaoCode) {
		this.icaoCode = icaoCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.airports.faa_lid
	 * @return  the value of public.airports.faa_lid
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public String getFaaLid() {
		return faaLid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.airports.faa_lid
	 * @param faaLid  the value for public.airports.faa_lid
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public void setFaaLid(String faaLid) {
		this.faaLid = faaLid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.airports.name
	 * @return  the value of public.airports.name
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.airports.name
	 * @param name  the value for public.airports.name
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.airports.wiki_url
	 * @return  the value of public.airports.wiki_url
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public String getWikiUrl() {
		return wikiUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.airports.wiki_url
	 * @param wikiUrl  the value for public.airports.wiki_url
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public void setWikiUrl(String wikiUrl) {
		this.wikiUrl = wikiUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.airports.latitude
	 * @return  the value of public.airports.latitude
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public Double getLatitude() {
		return latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.airports.latitude
	 * @param latitude  the value for public.airports.latitude
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.airports.longitude
	 * @return  the value of public.airports.longitude
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public Double getLongitude() {
		return longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.airports.longitude
	 * @param longitude  the value for public.airports.longitude
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.airports.iata_code
	 * @return  the value of public.airports.iata_code
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public String getIataCode() {
		return iataCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.airports.iata_code
	 * @param iataCode  the value for public.airports.iata_code
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public void setIataCode(String iataCode) {
		this.iataCode = iataCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.airports.locations_served_last_update
	 * @return  the value of public.airports.locations_served_last_update
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public Date getLocationsServedLastUpdate() {
		return locationsServedLastUpdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.airports.locations_served_last_update
	 * @param locationsServedLastUpdate  the value for public.airports.locations_served_last_update
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public void setLocationsServedLastUpdate(Date locationsServedLastUpdate) {
		this.locationsServedLastUpdate = locationsServedLastUpdate;
	}
}