package com.roughindustries.air.model;

public class Airports {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.airports.iata_code
	 * @mbggenerated  Thu Mar 24 13:07:15 CDT 2016
	 */
	private String iataCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.airports.icao_code
	 * @mbggenerated  Thu Mar 24 13:07:15 CDT 2016
	 */
	private String icaoCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.airports.faa_lid
	 * @mbggenerated  Thu Mar 24 13:07:15 CDT 2016
	 */
	private String faaLid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.airports.name
	 * @mbggenerated  Thu Mar 24 13:07:15 CDT 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.airports.wiki_url
	 * @mbggenerated  Thu Mar 24 13:07:15 CDT 2016
	 */
	private String wikiUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.airports.wiki_location_served
	 * @mbggenerated  Thu Mar 24 13:07:15 CDT 2016
	 */
	private String wikiLocationServed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.airports.wiki_location_server_url
	 * @mbggenerated  Thu Mar 24 13:07:15 CDT 2016
	 */
	private String wikiLocationServerUrl;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.airports.iata_code
	 * @return  the value of public.airports.iata_code
	 * @mbggenerated  Thu Mar 24 13:07:15 CDT 2016
	 */
	public String getIataCode() {
		return iataCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.airports.iata_code
	 * @param iataCode  the value for public.airports.iata_code
	 * @mbggenerated  Thu Mar 24 13:07:15 CDT 2016
	 */
	public void setIataCode(String iataCode) {
		this.iataCode = iataCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.airports.icao_code
	 * @return  the value of public.airports.icao_code
	 * @mbggenerated  Thu Mar 24 13:07:15 CDT 2016
	 */
	public String getIcaoCode() {
		return icaoCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.airports.icao_code
	 * @param icaoCode  the value for public.airports.icao_code
	 * @mbggenerated  Thu Mar 24 13:07:15 CDT 2016
	 */
	public void setIcaoCode(String icaoCode) {
		this.icaoCode = icaoCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.airports.faa_lid
	 * @return  the value of public.airports.faa_lid
	 * @mbggenerated  Thu Mar 24 13:07:15 CDT 2016
	 */
	public String getFaaLid() {
		return faaLid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.airports.faa_lid
	 * @param faaLid  the value for public.airports.faa_lid
	 * @mbggenerated  Thu Mar 24 13:07:15 CDT 2016
	 */
	public void setFaaLid(String faaLid) {
		this.faaLid = faaLid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.airports.name
	 * @return  the value of public.airports.name
	 * @mbggenerated  Thu Mar 24 13:07:15 CDT 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.airports.name
	 * @param name  the value for public.airports.name
	 * @mbggenerated  Thu Mar 24 13:07:15 CDT 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.airports.wiki_url
	 * @return  the value of public.airports.wiki_url
	 * @mbggenerated  Thu Mar 24 13:07:15 CDT 2016
	 */
	public String getWikiUrl() {
		return wikiUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.airports.wiki_url
	 * @param wikiUrl  the value for public.airports.wiki_url
	 * @mbggenerated  Thu Mar 24 13:07:15 CDT 2016
	 */
	public void setWikiUrl(String wikiUrl) {
		this.wikiUrl = wikiUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.airports.wiki_location_served
	 * @return  the value of public.airports.wiki_location_served
	 * @mbggenerated  Thu Mar 24 13:07:15 CDT 2016
	 */
	public String getWikiLocationServed() {
		return wikiLocationServed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.airports.wiki_location_served
	 * @param wikiLocationServed  the value for public.airports.wiki_location_served
	 * @mbggenerated  Thu Mar 24 13:07:15 CDT 2016
	 */
	public void setWikiLocationServed(String wikiLocationServed) {
		this.wikiLocationServed = wikiLocationServed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.airports.wiki_location_server_url
	 * @return  the value of public.airports.wiki_location_server_url
	 * @mbggenerated  Thu Mar 24 13:07:15 CDT 2016
	 */
	public String getWikiLocationServerUrl() {
		return wikiLocationServerUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.airports.wiki_location_server_url
	 * @param wikiLocationServerUrl  the value for public.airports.wiki_location_server_url
	 * @mbggenerated  Thu Mar 24 13:07:15 CDT 2016
	 */
	public void setWikiLocationServerUrl(String wikiLocationServerUrl) {
		this.wikiLocationServerUrl = wikiLocationServerUrl;
	}
}