package com.roughindustries.air.model;

public class Airport2airline {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.airport2airline.iata_airport_code
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	private String iataAirportCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.airport2airline.iata_airline_code
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	private String iataAirlineCode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.airport2airline.iata_airport_code
	 * @return  the value of public.airport2airline.iata_airport_code
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public String getIataAirportCode() {
		return iataAirportCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.airport2airline.iata_airport_code
	 * @param iataAirportCode  the value for public.airport2airline.iata_airport_code
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public void setIataAirportCode(String iataAirportCode) {
		this.iataAirportCode = iataAirportCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.airport2airline.iata_airline_code
	 * @return  the value of public.airport2airline.iata_airline_code
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public String getIataAirlineCode() {
		return iataAirlineCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.airport2airline.iata_airline_code
	 * @param iataAirlineCode  the value for public.airport2airline.iata_airline_code
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public void setIataAirlineCode(String iataAirlineCode) {
		this.iataAirlineCode = iataAirlineCode;
	}
}