package com.roughindustries.air.model;

public class LocationsServed {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.locations_served.internal_location_served_id
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	private Integer internalLocationServedId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.locations_served.latitude
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	private Double latitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.locations_served.longitude
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	private Double longitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.locations_served.name
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.locations_served.internal_location_served_id
	 * @return  the value of public.locations_served.internal_location_served_id
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public Integer getInternalLocationServedId() {
		return internalLocationServedId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.locations_served.internal_location_served_id
	 * @param internalLocationServedId  the value for public.locations_served.internal_location_served_id
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public void setInternalLocationServedId(Integer internalLocationServedId) {
		this.internalLocationServedId = internalLocationServedId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.locations_served.latitude
	 * @return  the value of public.locations_served.latitude
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public Double getLatitude() {
		return latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.locations_served.latitude
	 * @param latitude  the value for public.locations_served.latitude
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.locations_served.longitude
	 * @return  the value of public.locations_served.longitude
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public Double getLongitude() {
		return longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.locations_served.longitude
	 * @param longitude  the value for public.locations_served.longitude
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.locations_served.name
	 * @return  the value of public.locations_served.name
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.locations_served.name
	 * @param name  the value for public.locations_served.name
	 * @mbggenerated  Sat Apr 02 15:30:07 CDT 2016
	 */
	public void setName(String name) {
		this.name = name;
	}
}